### ISSUE TITLE
Criar roles Admin / User

### ISSUE THREAD

**Issue by pmarkun** [pmarkun/lex-firebase#8]
Criar campo 'role' ou algo parecido para criar sistema de permissão para admins e usuarios regulares.

Talvez algo que mapeie cada role para um numero.
5 guest
10 user
20 editor
50 admin

assim a gente não precisa de um sistema tão complexo mas pode fazer coisas tipo:

if (role > editor)

**Comment by luisleao** [comment]
Ajustando isso. Vou usar esse sistema numérico para permissões e já deixei uma coleção com as categorias principais.

O participante automaticamente vai para "user" caso faça uma doação. O contrário fica como guest ou com o perfil que tenha sido utilizado, que não seja guest.

**Comment by luisleao** [comment]
Implementado sistema de regras por base do usuário.
